#!/usr/bin/env bash
# Script to transfer a file from client to remote server
# Accepts 4 params:
#	1. path to file to transfer
#	2. IP of the server
#	3. The username scp connects with
#	4. Path to ssh private key to be used by scp
if [$# -ge 4]
then
  scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi    
