#!/usr/bin/env bash
# Script to install nginx webserver and serve file
# Nginx should listen on port 80
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     location /redirect_me {
	 return 301 http://google.com/;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
