#!/usr/bin/env bash
# Install Nginx and configure it with custom http header response
# Script to install nginx webserver and serve file
# Nginx should listen on port 80
sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
sudo echo "add_header X-Served-By \$host;" | sudo tee -a /etc/nginx/nginx.conf
service nginx restart

