#!/bin/bash

# Update the package list
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy -y

# Configure HAProxy
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server web-01 134710-web-01:80 check
    server web-02 134710-web-02:80 check
EOT

# Restart HAProxy
sudo service haproxy restart
