#!/usr/bin/env bash
# Output numbers from 1 to 100 in list format.
# Output "FizzBuzz" when the number is a multiple of 3 and 5.
# Output "Fizz" when the number is a multiple of 3.
# Output "Buzz" when the number is a multiple of 5.
# Otherwise, output the number.

for num in {1..100};
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi;
done
