#!/usr/bin/env bash
# Print the contents of the file `/etc/passwd`.
# Only output the username, user id, and user home directory path.

while read -r passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
