#!/usr/bin/env bash
# script to print numbers 1-20 and some strings in between
i=1
while [ $i -le 20 ]; do
	if [ "$i" = 4 ]
	then
		echo "bad luck from China"
	elif [ "$i" = 9 ]
	then 
		echo "bad luck from Japan"
	elif [ "$i" = 17 ]
	then
		echo "bad luck from Italy"
	else
		echo "$i"
	fi
	i=$((i+1))
done
