#!/usr/bin/env bash
# script to print numbers 1-20 and some strings in between
i=1
while [ $i -le 20 ]; do
	 case $i in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
		*)
		echo "$i"
	esac
	i=$((i+1))
done
