#!/usr/bin/env bash
# Configure nginx to run with user nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx stop
# Change the user that nginx runs as from www-data to nginx
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
