#!/usr/bin/env bash
# Configure nginx to run with user nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx stop
# Change the user that nginx runs as from www-data to nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;\n	listen [::]:8080 default_server;/' /etc/nginx/sites-enabled/default
sudo service nginx start
