#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install nginx
sudo service nginx stop
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/ listen 8080 default_server;\n	listen[::]:8080 defaulat_server;/' /etc/nginx/site-enabled/default
sudo service nginx start
